schema: spec-driven
created: 2026-09-01
goal: 完善 config 功能，目标是对私密配置进行加密存储：1. 配置管理应该是分组的，参考 env/text；2. 相比于
  env/text，配置应该新增 meta 信息，包含描述、保存位置；3. 支持安装操作，把单个/分组/全部配置安装到对应位置；4.
  安装时校验文件内容是否变化，有变化则需要先备份；5. 支持卸载操作，即删除对应位置的文件，如果文件有改动，需要确认，未改动则直接删除；6.
  安装/卸载操作本身需要先给出操作 plan (dry-run)，然后确认
skip_specs: true
