package ssh

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/wii/senv/internal/storage"
)

// DefaultFragmentPath is ~/.ssh/senv/groups/_default.conf: the local
// default keypair fragment (ADR-0025). Host Apply never rewrites it.
func DefaultFragmentPath() (string, error) {
	dir, err := groupsDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, defaultFragmentFile), nil
}

// DefaultIdentityFile returns the IdentityFile path recorded in
// _default.conf, or "" if unset/missing. The fragment is the source of
// truth; there is no vault pointer.
func DefaultIdentityFile() (string, error) {
	path, err := DefaultFragmentPath()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("read default keypair fragment: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, " ")
		if ok && strings.EqualFold(key, "IdentityFile") {
			return strings.TrimSpace(value), nil
		}
	}
	return "", nil
}

// ClearDefault removes _default.conf. Missing file is not an error.
func ClearDefault() error {
	path, err := DefaultFragmentPath()
	if err != nil {
		return err
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("clear default keypair: %w", err)
	}
	return nil
}

// SetDefaultKeyPair makes name the local default: materialize if missing,
// write Host * IdentityFile into _default.conf, and register the groups
// Include so OpenSSH sees it even without a host export.
func (m *Manager) SetDefaultKeyPair(name string) (string, error) {
	target, err := m.ensureMaterialized(name)
	if err != nil {
		return "", err
	}
	if err := writeDefaultFragment(target); err != nil {
		return "", err
	}
	if _, err := RegisterInclude(); err != nil {
		return "", fmt.Errorf("register include for default keypair: %w", err)
	}
	return target, nil
}

// DefaultKeyPairName resolves the current default IdentityFile back to a
// vault keypair name, or "" if unset or the path matches none.
func (m *Manager) DefaultKeyPairName() (string, error) {
	identity, err := DefaultIdentityFile()
	if err != nil || identity == "" {
		return "", err
	}
	pairs, err := m.ListKeyPairs()
	if err != nil {
		return "", err
	}
	for _, pair := range pairs {
		path, err := MaterializePath(pair.Group, pair.Name)
		if err != nil {
			return "", err
		}
		if path == identity {
			return pair.Name, nil
		}
	}
	return "", nil
}

func writeDefaultFragment(identityPath string) error {
	path, err := DefaultFragmentPath()
	if err != nil {
		return err
	}
	body := fmt.Sprintf("# generated by senv keypair set-default — do not edit\nHost *\n  IdentityFile %s\n", identityPath)
	if err := storage.WriteSensitiveFile(path, []byte(body), 0o700, 0o600); err != nil {
		return fmt.Errorf("write default keypair fragment: %w", err)
	}
	return nil
}

// ensureMaterialized writes the private key if the conventional path is
// missing; an existing private file is left untouched (no force). A missing
// sibling .pub is still filled in so older exports pick up the public file.
func (m *Manager) ensureMaterialized(name string) (string, error) {
	entry, err := m.loadKeyPair(name)
	if err != nil {
		return "", err
	}
	target, err := MaterializePath(entry.Group, entry.Name)
	if err != nil {
		return "", err
	}
	if _, statErr := os.Lstat(target); statErr == nil {
		if err := ensurePublicKeyFile(target, resolvedPublicKey(entry)); err != nil {
			return "", err
		}
		return target, nil
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return "", fmt.Errorf("inspect materialized key %q: %w", target, statErr)
	}
	return m.Materialize(name, false)
}

// syncDefaultIdentity rewrites or clears _default.conf when its IdentityFile
// still points at oldPath. newPath empty means the keypair was deleted.
func syncDefaultIdentity(oldPath, newPath string) error {
	if oldPath == "" {
		return nil
	}
	current, err := DefaultIdentityFile()
	if err != nil || current == "" || current != oldPath {
		return err
	}
	if newPath == "" {
		return ClearDefault()
	}
	return writeDefaultFragment(newPath)
}
