package ssh

import (
	"errors"
	"strings"
	"testing"

	"github.com/wii/senv/internal/storage"
)

func TestHostValidationBranches(t *testing.T) {
	mgr, _ := newTestSSHManager(t)
	host := &storage.HostEntry{Alias: "web", Hostname: "10.0.0.1", Port: 22}
	if err := mgr.AddHost(host); err != nil {
		t.Fatalf("valid host: %v", err)
	}
	if err := mgr.AddHost(host); !errors.Is(err, ErrExists) {
		t.Fatalf("duplicate error = %v", err)
	}
	cases := []struct {
		name string
		host *storage.HostEntry
		want string
	}{
		{"missing hostname", &storage.HostEntry{Alias: "a"}, "hostname is required"},
		{"bad alias", &storage.HostEntry{Alias: "../a", Hostname: "a"}, `invalid SSH host "../a"`},
		{"bad port", &storage.HostEntry{Alias: "a", Hostname: "a", Port: 70000}, "invalid SSH port"},
		{"blank tag", &storage.HostEntry{Alias: "a", Hostname: "a", Tags: []string{" "}}, "invalid SSH tag"},
		{"newline group", &storage.HostEntry{Alias: "a", Hostname: "a", Group: "prod\nwest"}, "group must not contain"},
		{"slash group", &storage.HostEntry{Alias: "a", Hostname: "a", Group: "prod/west"}, "group must not contain"},
		{"blank attr key", &storage.HostEntry{Alias: "a", Hostname: "a", Extra: map[string]string{" ": "x"}}, "invalid SSH attribute key"},
		{"newline attr", &storage.HostEntry{Alias: "a", Hostname: "a", Extra: map[string]string{"X": "a\nb"}}, "value must not contain"},
	}
	for _, tc := range cases {
		if err := mgr.AddHost(tc.host); err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Fatalf("%s: err = %v, want %q", tc.name, err, tc.want)
		}
	}
	if err := mgr.AddHost(&storage.HostEntry{Alias: "relay", Hostname: "relay"}); err != nil {
		t.Fatal(err)
	}
	if err := mgr.AddHost(&storage.HostEntry{Alias: "through", Hostname: "through", ProxyJump: "relay"}); err != nil {
		t.Fatalf("valid proxy: %v", err)
	}
	if err := mgr.AddHost(&storage.HostEntry{Alias: "bad", Hostname: "bad", ProxyJump: "missing"}); err == nil || !strings.Contains(err.Error(), "missing") {
		t.Fatalf("dangling proxy error = %v", err)
	}
	if err := mgr.AddHost(&storage.HostEntry{Alias: "self", Hostname: "self", ProxyJump: "self"}); err == nil {
		t.Fatal("self proxy accepted")
	}
}

func TestUpdateHostValidatesResultingRecord(t *testing.T) {
	mgr, _ := newTestSSHManager(t)
	path := writePrivateKey(t, t.TempDir(), ed25519Private(t), "update@test", "")
	if _, err := mgr.ImportKeyPair("update-key", path, false); err != nil {
		t.Fatal(err)
	}
	if err := mgr.AddHost(&storage.HostEntry{Alias: "web", Hostname: "old"}); err != nil {
		t.Fatal(err)
	}
	err := mgr.UpdateHost("web", func(host *storage.HostEntry) error {
		host.IdentityKey = "update-key"
		return nil
	})
	if err != nil {
		t.Fatalf("update: %v", err)
	}
	host, err := mgr.GetHost("web")
	if err != nil || host.IdentityKey != "update-key" {
		t.Fatalf("updated host = %+v, %v", host, err)
	}
	if err := mgr.UpdateHost("web", func(host *storage.HostEntry) error {
		host.IdentityKey = "missing"
		return nil
	}); err == nil {
		t.Fatal("dangling identity accepted")
	}
	// 编辑路径同样禁止含 / 的组名。
	if err := mgr.UpdateHost("web", func(host *storage.HostEntry) error {
		host.Group = "a/b"
		return nil
	}); err == nil || !strings.Contains(err.Error(), "group must not contain") {
		t.Fatalf("slash group update error = %v", err)
	}
}

func concatFragments(rr *RenderResult) string {
	var b strings.Builder
	for _, group := range rr.Order {
		b.WriteString(rr.Fragments[group])
	}
	return b.String()
}

func TestHostRenderGolden(t *testing.T) {
	mgr, _ := newTestSSHManager(t)
	t.Setenv("HOME", "/home/test-user")
	path := writePrivateKey(t, t.TempDir(), ed25519Private(t), "golden@test", "")
	if _, err := mgr.ImportKeyPair("golden-key", path, false); err != nil {
		t.Fatal(err)
	}
	if err := mgr.AddHost(&storage.HostEntry{
		Alias:       "jump",
		Hostname:    "jump.example",
		User:        "jump",
		Port:        2222,
		IdentityKey: "golden-key",
		Extra:       map[string]string{"IdentitiesOnly": "yes"},
	}); err != nil {
		t.Fatal(err)
	}
	if err := mgr.AddHost(&storage.HostEntry{
		Alias:     "web",
		Hostname:  "10.0.0.1",
		User:      "deploy",
		Port:      22,
		ProxyJump: "jump",
		Extra:     map[string]string{"ForwardAgent": "yes"},
	}); err != nil {
		t.Fatal(err)
	}
	rr, err := mgr.Render(RenderFilter{})
	if err != nil {
		t.Fatal(err)
	}
	if len(rr.Order) != 1 || rr.Order[0] != "" {
		t.Fatalf("order = %v, want single ungrouped fragment", rr.Order)
	}
	want := `# generated by senv host export — do not edit
# group: _ungrouped
Host jump
  HostName jump.example
  User jump
  Port 2222
  IdentityFile /home/test-user/.ssh/senv/keys/_ungrouped/golden-key
  IdentitiesOnly yes
Host web
  HostName 10.0.0.1
  User deploy
  Port 22
  ProxyJump jump
  ForwardAgent yes
`
	if got := rr.Fragments[""]; got != want {
		t.Fatalf("render mismatch:\n got:\n%s\nwant:\n%s", got, want)
	}
	// 单 host 预览：含该 host 及其 ProxyJump 闭包（连通性前提）。
	single, err := mgr.Render(RenderFilter{Host: "web"})
	if err != nil {
		t.Fatal(err)
	}
	if got := single.Fragments[""]; !strings.Contains(got, "Host jump\n") ||
		!strings.Contains(got, "Host web\n") ||
		!strings.HasPrefix(got, "# generated by senv host export") {
		t.Fatalf("single render = %q", got)
	}
}

func TestRenderDanglingProxyFails(t *testing.T) {
	mgr, store := newTestSSHManager(t)
	if err := store.WithVaultMutation(func(locked *storage.Manager) error {
		return locked.SaveHost("web", &storage.HostEntry{Alias: "web", Hostname: "web", ProxyJump: "gone"}, "test-password")
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := mgr.Render(RenderFilter{}); err == nil || !strings.Contains(err.Error(), "gone") {
		t.Fatalf("dangling render error = %v", err)
	}
}

func TestRenderWarnsOnMissingIdentityKeypair(t *testing.T) {
	mgr, store := newTestSSHManager(t)
	t.Setenv("HOME", "/home/test-user")
	path := writePrivateKey(t, t.TempDir(), ed25519Private(t), "present@test", "")
	if _, err := mgr.ImportKeyPair("present-key", path, false); err != nil {
		t.Fatal(err)
	}
	// 绕过 Manager 层引用校验，构造「host 档案先同步到、keypair 未到」的
	// 跨机悬空（ADR-0020 D4）。
	if err := store.WithVaultMutation(func(locked *storage.Manager) error {
		return locked.SaveHost("dangling", &storage.HostEntry{
			Alias: "dangling", Hostname: "d.example", IdentityKey: "absent-key",
		}, "test-password")
	}); err != nil {
		t.Fatal(err)
	}
	if err := mgr.AddHost(&storage.HostEntry{
		Alias: "ok", Hostname: "ok.example", IdentityKey: "present-key",
	}); err != nil {
		t.Fatal(err)
	}

	rr, err := mgr.Render(RenderFilter{})
	if err != nil {
		t.Fatal(err)
	}
	if len(rr.Warnings) != 1 || !strings.Contains(rr.Warnings[0], "host dangling 引用的 keypair absent-key 不在本机 vault") {
		t.Fatalf("warnings = %v, want one dangling warning", rr.Warnings)
	}
	got := concatFragments(rr)
	// 分组未知时按未分组占位渲染；同步到位后下一次导出会重渲染为真实分组路径。
	if !strings.Contains(got, "IdentityFile /home/test-user/.ssh/senv/keys/_ungrouped/absent-key") {
		t.Fatalf("dangling host block missing IdentityFile:\n%s", got)
	}
	if !strings.Contains(got, "Host ok") {
		t.Fatalf("other hosts must still be rendered:\n%s", got)
	}

	// 过滤到无悬空的 host：不应产生 warning
	single, err := mgr.Render(RenderFilter{Host: "ok"})
	if err != nil || len(single.Warnings) != 0 {
		t.Fatalf("ok render warnings = %v, err = %v, want none", single.Warnings, err)
	}
	if !strings.Contains(single.Fragments[""], "Host ok") {
		t.Fatalf("single render = %q", single.Fragments[""])
	}
}

func TestRenderGroupsHostsAndClosure(t *testing.T) {
	mgr, _ := newTestSSHManager(t)
	t.Setenv("HOME", "/home/test-user")
	keyPath := writePrivateKey(t, t.TempDir(), ed25519Private(t), "grp@test", "")
	if _, err := mgr.ImportKeyPairWithGroup("prod-key", keyPath, "prod", false); err != nil {
		t.Fatal(err)
	}
	if _, err := mgr.ImportKeyPairWithGroup("net-key", keyPath, "network", false); err != nil {
		t.Fatal(err)
	}
	add := func(h *storage.HostEntry) {
		t.Helper()
		if err := mgr.AddHost(h); err != nil {
			t.Fatal(err)
		}
	}
	add(&storage.HostEntry{Alias: "bastion", Hostname: "192.0.2.1", Group: "network", IdentityKey: "net-key"})
	add(&storage.HostEntry{Alias: "web", Hostname: "10.0.0.1", Group: "prod", IdentityKey: "prod-key", ProxyJump: "bastion"})
	add(&storage.HostEntry{Alias: "api", Hostname: "10.0.0.2", Group: "prod"})

	// 组过滤：闭包目标并入发起组片段，目标所属组片段仅在该组被选中时出现。
	rr, err := mgr.Render(RenderFilter{Group: "prod"})
	if err != nil {
		t.Fatal(err)
	}
	if len(rr.Order) != 1 || rr.Order[0] != "prod" {
		t.Fatalf("order = %v, want [prod]", rr.Order)
	}
	prod := rr.Fragments["prod"]
	for _, want := range []string{"Host api\n", "Host bastion\n", "Host web\n", "IdentityFile /home/test-user/.ssh/senv/keys/prod/prod-key"} {
		if !strings.Contains(prod, want) {
			t.Fatalf("prod fragment missing %q:\n%s", want, prod)
		}
	}
	// 闭包块的 IdentityFile 按其 keypair 真实分组（network）渲染进 prod 片段。
	if strings.Count(prod, "Host bastion\n") != 1 {
		t.Fatalf("closure block must render exactly once:\n%s", prod)
	}

	// 全量：三个 host 分属两个组片段。
	all, err := mgr.Render(RenderFilter{})
	if err != nil {
		t.Fatal(err)
	}
	if len(all.Order) != 2 || all.Order[0] != "network" || all.Order[1] != "prod" {
		t.Fatalf("order = %v, want [network prod]", all.Order)
	}
	if strings.Contains(all.Fragments["network"], "Host web\n") {
		t.Fatalf("network fragment must not contain prod hosts:\n%s", all.Fragments["network"])
	}

	// 未知组报错。
	if _, err := mgr.Render(RenderFilter{Group: "missing"}); err == nil || !strings.Contains(err.Error(), "not found") {
		t.Fatalf("missing group error = %v", err)
	}
}

func TestRenderUngroupedNameCollision(t *testing.T) {
	mgr, _ := newTestSSHManager(t)
	// 真实组名占用保留名 + 存在未分组 host → 拒绝渲染。
	if err := mgr.AddHost(&storage.HostEntry{Alias: "real", Hostname: "r", Group: "_ungrouped"}); err != nil {
		t.Fatal(err)
	}
	if err := mgr.AddHost(&storage.HostEntry{Alias: "free", Hostname: "f"}); err != nil {
		t.Fatal(err)
	}
	if _, err := mgr.Render(RenderFilter{}); err == nil || !strings.Contains(err.Error(), "reserved") {
		t.Fatalf("collision error = %v", err)
	}
	// 全部有真实分组（含 _ungrouped 组）而无未分组槽位使用 → 正常。
	mgr2, _ := newTestSSHManager(t)
	if err := mgr2.AddHost(&storage.HostEntry{Alias: "real", Hostname: "r", Group: "_ungrouped"}); err != nil {
		t.Fatal(err)
	}
	if _, err := mgr2.Render(RenderFilter{}); err != nil {
		t.Fatalf("real _ungrouped group without ungrouped slot: %v", err)
	}
}
